# Generated by Django 3.2.7 on 2021-09-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('cat_description', models.TextField(blank=True)),
                ('cat_image', models.ImageField(upload_to='images/categories')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
